net start msexchangesa
net start msexchangetransport
net start msexchangetransportlogsearch
net start msexchangeAdtopology
net start msexchangeantispamupdate
net start msexchangeedgesync
net start msexchangefds
net start msexchangeimap4
net start msexchangeis
net start msexchangemailsubmission
net start msexchangemailboxassistants
net start msexchangepop3
net start msexchangerepl
net start msexchangesearch
net start msexchangeservicehost
net start msspeechservice
net start msexchangeum