net stop msexchangesa /y
net stop msexchangetransport /y
net stop msexchangetransportlogsearch /y
net stop msexchangeAdtopology /y
net stop msexchangeantispamupdate /y
net stop msexchangeedgesync /y
net stop msexchangefds /y
net stop msexchangeimap4 /y
net stop msexchangeis /y
net stop msexchangemailsubmission /y
net stop msexchangemailboxassistants /y
net stop msexchangepop3 /y
net stop msexchangerepl /y
net stop msexchangesearch /y
net stop msexchangeservicehost /y
net stop msspeechservice /y
net stop msexchangeum /y